.de1 NOP
.  it 1 an-trap
.  if \\n[.$] \,\\$*\/
..
.ie t \
.ds B-Font [CB]
.ds I-Font [CI]
.ds R-Font [CR]
.el \
.ds B-Font B
.ds I-Font I
.ds R-Font R
.TH ocsptool 1 "10 Mar 2022" "3.7.4" "User Commands"
.SH NAME
\f\*[B-Font]ocsptool\fP
\- GnuTLS OCSP tool
.SH SYNOPSIS
\f\*[B-Font]ocsptool\fP
.\" Mixture of short (flag) options and long options
[\f\*[B-Font]\-flags\f[]]
[\f\*[B-Font]\-flag\f[] [\f\*[I-Font]value\f[]]]
[\f\*[B-Font]\-\-option-name\f[][[=| ]\f\*[I-Font]value\f[]]]
.sp \n(Ppu
.ne 2

All arguments must be options.
.sp \n(Ppu
.ne 2
.SH "DESCRIPTION"
ocsptool is a program that can parse and print information about
OCSP requests/responses, generate requests and verify responses. Unlike
other GnuTLS applications it outputs DER encoded structures by default
unless the '--outpem' option is specified.
.sp
.SH "OPTIONS"
.TP
.NOP \f\*[B-Font]\-d\f[] \f\*[I-Font]num\f[], \f\*[B-Font]\-\-debug\f[]=\f\*[I-Font]num\f[]
Enable debugging.
This option takes an integer number as its argument.
The value of
\f\*[I-Font]num\f[]
is constrained to being:
.in +4
.nf
.na
in the range 0 through 9999
.fi
.in -4
.sp
Specifies the debug level.
.TP
.NOP \f\*[B-Font]\-V\f[], \f\*[B-Font]\-\-verbose\f[]
More verbose output.
.sp
.TP
.NOP \f\*[B-Font]\-\-infile\f[]=\f\*[I-Font]file\f[]
Input file.
.sp
.TP
.NOP \f\*[B-Font]\-\-outfile\f[]=\f\*[I-Font]str\f[]
Output file.
.sp
.TP
.NOP \f\*[B-Font]\-\-ask\f[]=\f\*[I-Font]server name|url\f[]
Ask an OCSP/HTTP server on a certificate validity.
.sp
Connects to the specified HTTP OCSP server and queries on the validity of the loaded certificate.
Its argument can be a URL or a plain server name. It can be combined with \-\-load\-chain, where it checks
all certificates in the provided chain, or with \-\-load\-cert and
\-\-load\-issuer options. The latter checks the provided certificate
against its specified issuer certificate.
.TP
.NOP \f\*[B-Font]\-e\f[], \f\*[B-Font]\-\-verify\-response\f[]
Verify response.
.sp
Verifies the provided OCSP response against the system trust
anchors (unless \-\-load\-trust is provided). It requires the \-\-load\-signer
or \-\-load\-chain options to obtain the signer of the OCSP response.
.TP
.NOP \f\*[B-Font]\-i\f[], \f\*[B-Font]\-\-request\-info\f[]
Print information on a OCSP request.
.sp
Display detailed information on the provided OCSP request.
.TP
.NOP \f\*[B-Font]\-j\f[], \f\*[B-Font]\-\-response\-info\f[]
Print information on a OCSP response.
.sp
Display detailed information on the provided OCSP response.
.TP
.NOP \f\*[B-Font]\-q\f[], \f\*[B-Font]\-\-generate\-request\f[]
Generates an OCSP request.
.sp
.TP
.NOP \f\*[B-Font]\-\-nonce\f[], \f\*[B-Font]\-\-no\-nonce\f[]
Use (or not) a nonce to OCSP request.
The \fIno\-nonce\fP form will disable the option.
.sp
.TP
.NOP \f\*[B-Font]\-\-load\-chain\f[]=\f\*[I-Font]file\f[]
Reads a set of certificates forming a chain from file.
.sp
.TP
.NOP \f\*[B-Font]\-\-load\-issuer\f[]=\f\*[I-Font]file\f[]
Reads issuer's certificate from file.
.sp
.TP
.NOP \f\*[B-Font]\-\-load\-cert\f[]=\f\*[I-Font]file\f[]
Reads the certificate to check from file.
.sp
.TP
.NOP \f\*[B-Font]\-\-load\-trust\f[]=\f\*[I-Font]file\f[]
Read OCSP trust anchors from file.
This option must not appear in combination with any of the following options:
load-signer.
.sp
When verifying an OCSP response read the trust anchors from the
provided file. When this is not provided, the system's trust anchors will be
used.
.TP
.NOP \f\*[B-Font]\-\-load\-signer\f[]=\f\*[I-Font]file\f[]
Reads the OCSP response signer from file.
This option must not appear in combination with any of the following options:
load-trust.
.sp
.TP
.NOP \f\*[B-Font]\-\-inder\f[], \f\*[B-Font]\-\-no\-inder\f[]
Use DER format for input certificates and private keys.
The \fIno\-inder\fP form will disable the option.
.sp
.TP
.NOP \f\*[B-Font]\-\-outder\f[]
Use DER format for output of responses (this is the default).
.sp
The output will be in DER encoded format. Unlike other GnuTLS tools, this is the default for this tool
.TP
.NOP \f\*[B-Font]\-\-outpem\f[]
Use PEM format for output of responses.
.sp
The output will be in PEM format.
.TP
.NOP \f\*[B-Font]\-Q\f[] \f\*[I-Font]file\f[], \f\*[B-Font]\-\-load\-request\f[]=\f\*[I-Font]file\f[]
Reads the DER encoded OCSP request from file.
.sp
.TP
.NOP \f\*[B-Font]\-S\f[] \f\*[I-Font]file\f[], \f\*[B-Font]\-\-load\-response\f[]=\f\*[I-Font]file\f[]
Reads the DER encoded OCSP response from file.
.sp
.TP
.NOP \f\*[B-Font]\-\-ignore\-errors\f[]
Ignore any verification errors.
.sp
.TP
.NOP \f\*[B-Font]\-\-verify\-allow\-broken\f[]
Allow broken algorithms, such as MD5 for verification.
.sp
This can be combined with \-\-verify\-response.
.TP
.NOP \f\*[B-Font]\-v\f[] \f\*[I-Font]arg\f[], \f\*[B-Font]\-\-version\f[]=\f\*[I-Font]arg\f[]
Output version of program and exit.  The default mode is `v', a simple
version.  The `c' mode will print copyright information and `n' will
print the full copyright notice.
.TP
.NOP \f\*[B-Font]\-h\f[], \f\*[B-Font]\-\-help\f[]
Display usage information and exit.
.TP
.NOP \f\*[B-Font]\-!\f[], \f\*[B-Font]\-\-more\-help\f[]
Pass the extended usage information through a pager.

.SH "EXIT STATUS"
One of the following exit values will be returned:
.TP
.NOP 0 " (EXIT_SUCCESS)"
Successful program execution.
.TP
.NOP 1 " (EXIT_FAILURE)"
The operation failed or the command syntax was not valid.
.PP
.SH "AUTHORS"

.SH "COPYRIGHT"
Copyright (C) 2022 Daiki Ueno
This program is released under the terms of
the GNU General Public License, version 3 or later
.
